version: '3.7'
  
services:
  etl:
    image: "etl"
    build: ./
    environment:
      TZ: "America/Santiago"
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./core/elt.py:/root/ 
    command: "python3 -m etl.py"
                 
  backend:
    image: "games_api"
    build: ./
    environment:
      TZ: "America/Santiago"
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on: 
      - etl
    volumes:
      - ./:/root/ 
    command: "uvicorn main:app --reload --workers 1 --host localhost --port 8080"
               
    ports:
      - 8080:8080 